"""empty message

Revision ID: 2c858a4bd942
Revises: acaf5a383b95
Create Date: 2022-01-17 15:32:57.778981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c858a4bd942'
down_revision = 'acaf5a383b95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('title', table_name='question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('title', 'question', ['title'], unique=False)
    # ### end Alembic commands ###
